os: linux
dist: trusty
cache: false
sudo: required
language: bash
services: docker
env:
  matrix:
    - ARCH=x86_64 DISTRIB=debian
    - ARCH=x86_64 DISTRIB=alpine
    - ARCH=armhf DISTRIB=debian
    - ARCH=armhf DISTRIB=alpine
  global:
  - secure: aDZcVDUhVYVLGGsJNmUj6uNVI1WLRptqhjK3btynC9iTUDmB1ISIVe/X96HSzHjQa1fQsqVDq7t64PdJRfZVxU4vEpB61hXG8wbl/lJ6nbIMvclxpf5yKgmxW4Hng3fd+Qc0PZSlw6dP5XXMGLjzTbUjEz/QfPJX+cNTg6b7hV7lh2lNdZbBzulvknrU9rTz+EkLqBJLtW5DlKdsV9cKgMOf5wT8Uss1q3o2+nQ7Y5q3FYo1g8y+Gi58oedK8rk6LF1f0qW4lrd0YDMuLRJYoILyTWX3gHwA4u8Dsritl58i7TDOsMtbfuMMwjMPJ6GNd7lQyqdFwgSX1ufU4aouPaEpDtkLqVtYc4c6MOD3eR5GXQllh4D6dBpMtt9GSV7S0pdQNDBKuA8wKLR7bSkNeMxh22qJUrxk+McTtsxuydnGVbTYMPTkzi8lYTLm5eQoVCxi1fQsEFTG/bETxb4WWvGvqFy224g7Y2u3fcPiw57EeoNHkGwhWSOzls1K0vNZvwmbVWKuOawsaE6Z3OtFRFjp/9UhMqQVi/pOKE8BMRRv9cQ9l/USGk8uBEP69Ort5o0xS5QYMdMzwfyamHhcRGluxy84y1R5gkf9M9vt5T9DJJ7wO9Xr/UB4mvhq7hoKz8WT0tbOaumHSKgHdw62n1h9W6VNU5Au4ZYgxoBR3+E=
  - secure: P8KqNUxsJU9TFn4GefvPU5ctdAsDdqEJFNMQbTvrWpjBfHW33va/BDku/5cmWVjhGNVGt+UubU8iXSb5UgqV20yDcPaXqQoOhtZZuuuRiqZhBiUHr4cUjA5EJWTBQXFTWulv14bLjbrgasDbJZlap5FkyL9VUkf4Jqt/9gtax9DYNldcwZ1WuOpH9wn3Xv2d4vsr9lR9T9qtEyJBKDHcKb3WzNsOHdq9soYWiN/dWTayIImTOz3hN/jgGo7an2/I4uwILRqiK+xfjz60WQ74+YYqZgateDogb57p87pYWp8pDlAtUSa3t7LDwfzOW/G/z64LLhv1KEO+2hD3zoyC+VDx4bqMTuBWMdy70wSXdajL8UFXl3oU6p0kPgFwQTziCYwIrdmY5GKqhDVISq1199E7yUQNMuPmTXxUgr/+CyYyCImu0X6tMpSn0Hcsbs/18hCNBADHHlkzhImE2CqMXwAbga87kCXG3I6AgJHZ4+b6pMU2fBCDklCFRisenyWv5Mt8SVyb2XF63DTcT37ZL8FsWK5PSrJAcBe+BlS/mhCS5MrsLVYJdAm8hIEhanZ0euAjyyZvjd7kJkIuFmClBSIJ+c/i1ktvLdNawZf17TKjQDinFd1IDNYcWPUt6Hc3qw8pmOzYby9jGNFzFjBhtbR6BxsxZntZfm4zcoVLSx8=
  - secure: f3UuB36ga3fKub85U54XEI1xU90cK5ygJDJbs/WtO6Sl7nUAQzlZ/L9dK3txSJk8Lquy4wRm06bH3awB4pUdFaNnFfinoVy/FscgBkN8lflLUU6b3tlcy9DoYSkSDixES/VTs/C0ClOxJwjgkZdAAiuRD7d+I2T3jv7n7PxvrpL0QXF2pFNYzbI4i0MEr9s2iPC2vuGceXNeearoDVLX3zHJQVGhqLE8i62mAg+0cIKry4oabqixtx1FzkLZpQJzgYrD4zSznzA4ZlCeqr4qUuG5EWdfQrEHzI041kOZaiT6+/Leq8R75sCK4XLVnH6GteCS0zOdo0ytIncVCd1FWZ3V5w20MLmPznNnoD+dnHjBEV7g7MgA98AGV0e7aWnxZh1Sg6Lg+zbDsNzeZ4YZ7xRXNJppdSMmx4ShymNrPZHKrSG/ie6yHIDOit1DN4nE+MCNDSJO3Bsyn7fxFv1JKwjpjhH+gNVgTkz9NGyQeXrXjbufLYKo1l7964cVd7En7tbFaeHdb8z1ap2svZx3PUSfIjbeiiFJh2FErVNgwylSsnqds48d3ctWmS0foygG/2Gn7kznf1cnu3JZeyQzDOZ8ZaYgv4K4xuigRX14TxMAHG+bZ1xdtBBIKkX5KYgy6ZXxFnqV8m9toZMhczplvEpxXbkh+KUV0UYCX1/PXy4=
install: true
before_script:
- docker --version
- make --version
script:
  - make ARCH=${ARCH} DISTRIB=${DISTRIB} build test
after_success:
- docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
- make ARCH=${ARCH} DISTRIB=${DISTRIB} push
after_script:
- docker logout
- make clean
